In [3]:
import numpy as np
matrix = np.array([[2, 1],[5, 3]])
np.linalg.inv(matrix)

array([[ 3., -1.],
       [-5.,  2.]])

In [6]:
import numpy as np
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [7]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
np.multiply(a, b)

array([[ 5, 12],
       [21, 32]])

In [8]:
a = ([[1, 2, 3],

[4, 5, 6], [7, 8, 9]])

np.linalg.matrix_rank(a)

np.int64(2)

In [10]:
a = np.array([[10, 11, 12],

[13, 14, 15],

[16, 17, 18]])
a.diagonal()

array([10, 14, 18])

In [11]:
a = np.array([[10, 11, 12],

[13, 14, 15],

[16, 17, 18]])

a.trace()

np.int64(42)